# Generated by Django 5.0.1 on 2025-12-27 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("other_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "companies",
                "managed": True,
                "indexes": [
                    models.Index(fields=["slug"], name="companies_slug_e0676c_idx"),
                    models.Index(
                        fields=["created_at"], name="companies_created_c84a3d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("call_sid", models.TextField(blank=True, null=True)),
                ("caller_number", models.TextField(blank=True, null=True)),
                ("destination_number", models.TextField(blank=True, null=True)),
                ("direction", models.TextField(blank=True, null=True)),
                ("caller_info", models.TextField(blank=True, null=True)),
                ("filename", models.TextField(blank=True, null=True)),
                ("audio_url", models.TextField(blank=True, null=True)),
                ("user_uploaded", models.BooleanField(default=False)),
                ("call_started_at", models.DateTimeField(blank=True, null=True)),
                ("call_ended_at", models.DateTimeField(blank=True, null=True)),
                ("call_duration", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "calls",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_memberships",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ScorecardSystemPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_key", models.TextField()),
                ("name", models.TextField(blank=True, null=True)),
                ("segment", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("system_prompt", models.TextField()),
                ("model", models.TextField(blank=True, null=True)),
                ("model_metadata", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_system_prompts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SummarySystemPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_key", models.TextField()),
                ("name", models.TextField(blank=True, null=True)),
                ("segment", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("system_prompt", models.TextField()),
                ("model", models.TextField(blank=True, null=True)),
                ("model_metadata", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "summary_system_prompts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transcription_type", models.TextField()),
                ("transcript", models.TextField(blank=True, null=True)),
                ("segments", models.JSONField(blank=True, null=True)),
                ("speaker_count", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("transcript_platform", models.TextField(blank=True, null=True)),
                ("transcript_model", models.TextField(blank=True, null=True)),
                ("scorecard_model", models.TextField(blank=True, null=True)),
                ("summary_model", models.TextField(blank=True, null=True)),
                ("models_metadata", models.JSONField(blank=True, null=True)),
                ("call_summary", models.TextField(blank=True, null=True)),
                ("call_summary_error", models.TextField(blank=True, null=True)),
                (
                    "call_summary_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("call_scorecard", models.JSONField(blank=True, null=True)),
                ("call_scorecard_error", models.TextField(blank=True, null=True)),
                (
                    "call_scorecard_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.call"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TranscriptEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sequence_number", models.IntegerField()),
                ("timestamp_ms", models.BigIntegerField(blank=True, null=True)),
                ("speaker", models.TextField(blank=True, null=True)),
                ("text_chunk", models.TextField(blank=True, null=True)),
                ("pii_redacted", models.BooleanField(default=False)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.call",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transcript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcript_events",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["company"], name="calls_company_b8339d_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["user"], name="calls_user_id_0081d9_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["created_at"], name="calls_created_e2f5c6_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["call_sid"], name="calls_call_si_629561_idx"),
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(fields=["user"], name="company_mem_user_id_bdb144_idx"),
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(
                fields=["company"], name="company_mem_company_1384b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(
                fields=["created_at"], name="company_mem_created_be33ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="company_memberships_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(
                fields=["company"], name="scorecard_s_company_c976e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(
                fields=["is_active"], name="scorecard_s_is_acti_9868f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(
                fields=["created_at"], name="scorecard_s_created_e76546_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecardsystemprompt",
            constraint=models.UniqueConstraint(
                fields=("company", "prompt_key", "version"),
                name="scorecard_prompts_unique_version",
            ),
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(
                fields=["company"], name="summary_sys_company_a51fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(
                fields=["is_active"], name="summary_sys_is_acti_4ae24b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(
                fields=["created_at"], name="summary_sys_created_e246a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="summarysystemprompt",
            constraint=models.UniqueConstraint(
                fields=("company", "prompt_key", "version"),
                name="summary_prompts_unique_version",
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["call"], name="transcripts_call_id_65ea20_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["company"], name="transcripts_company_8dc355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["user"], name="transcripts_user_id_d35a60_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["created_at"], name="transcripts_created_6f4f1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(
                fields=["transcript"], name="transcript__transcr_af4d75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["call"], name="transcript__call_id_efe2c0_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(
                fields=["company"], name="transcript__company_995f9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["user"], name="transcript__user_id_3e3430_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(
                fields=["sequence_number"], name="transcript__sequenc_29245f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(
                fields=["created_at"], name="transcript__created_d9fff5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transcriptevent",
            constraint=models.UniqueConstraint(
                fields=("transcript", "sequence_number"),
                name="transcript_events_unique_seq",
            ),
        ),
    ]
