# Generated by Django 5.0.1 on 2025-12-26 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False
    atomic = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("other_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "companies",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="app_companies_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["created_at"], name="app_companies_created_at_idx"),
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("call_sid", models.TextField(blank=True, null=True)),
                ("caller_number", models.TextField(blank=True, null=True)),
                ("destination_number", models.TextField(blank=True, null=True)),
                ("direction", models.TextField(blank=True, null=True)),
                ("caller_info", models.TextField(blank=True, null=True)),
                ("filename", models.TextField(blank=True, null=True)),
                ("audio_url", models.TextField(blank=True, null=True)),
                ("user_uploaded", models.BooleanField(default=False)),
                ("call_started_at", models.DateTimeField(blank=True, null=True)),
                ("call_ended_at", models.DateTimeField(blank=True, null=True)),
                ("call_duration", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calls",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["company"], name="app_calls_company_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["user"], name="app_calls_user_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["created_at"], name="app_calls_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["call_sid"], name="app_calls_call_sid_idx"),
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_memberships",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(fields=["user"], name="app_company_memberships_user_idx"),
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(fields=["company"], name="app_company_memberships_company_idx"),
        ),
        migrations.AddIndex(
            model_name="companymembership",
            index=models.Index(fields=["created_at"], name="app_company_memberships_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_user_company"
            ),
        ),
        migrations.CreateModel(
            name="ScorecardSystemPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("segment", models.TextField()),
                ("version", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("system_prompt", models.TextField()),
                ("model", models.TextField()),
                ("model_metadata", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "scorecard_system_prompts",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(fields=["company"], name="app_scorecard_system_prompts_company_idx"),
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(fields=["is_active"], name="app_scorecard_system_prompts_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="scorecardsystemprompt",
            index=models.Index(fields=["created_at"], name="app_scorecard_system_prompts_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="scorecardsystemprompt",
            constraint=models.UniqueConstraint(
                fields=("company", "segment", "version"),
                name="unique_scorecard_prompt_version_per_company",
            ),
        ),
        migrations.CreateModel(
            name="SummarySystemPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("segment", models.TextField()),
                ("version", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("system_prompt", models.TextField()),
                ("model", models.TextField()),
                ("model_metadata", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "summary_system_prompts",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(fields=["company"], name="app_summary_system_prompts_company_idx"),
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(fields=["is_active"], name="app_summary_system_prompts_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="summarysystemprompt",
            index=models.Index(fields=["created_at"], name="app_summary_system_prompts_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="summarysystemprompt",
            constraint=models.UniqueConstraint(
                fields=("company", "segment", "version"),
                name="unique_summary_prompt_version_per_company",
            ),
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transcription_type", models.TextField()),
                ("transcript", models.TextField(blank=True, null=True)),
                ("segments", models.JSONField(blank=True, null=True)),
                ("speaker_count", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("transcript_platform", models.TextField(blank=True, null=True)),
                ("transcript_model", models.TextField(blank=True, null=True)),
                ("scorecard_model", models.TextField(blank=True, null=True)),
                ("summary_model", models.TextField(blank=True, null=True)),
                ("models_metadata", models.JSONField(blank=True, null=True)),
                ("call_summary", models.TextField(blank=True, null=True)),
                ("call_summary_error", models.TextField(blank=True, null=True)),
                (
                    "call_summary_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("call_scorecard", models.JSONField(blank=True, null=True)),
                ("call_scorecard_error", models.TextField(blank=True, null=True)),
                (
                    "call_scorecard_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.call"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["call"], name="app_transcripts_call_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["company"], name="app_transcripts_company_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["user"], name="app_transcripts_user_idx"),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(fields=["created_at"], name="app_transcripts_created_at_idx"),
        ),
        migrations.CreateModel(
            name="TranscriptEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence_number", models.IntegerField()),
                ("timestamp_ms", models.BigIntegerField()),
                ("speaker", models.TextField(blank=True, null=True)),
                ("text_chunk", models.TextField(blank=True, null=True)),
                ("pii_redacted", models.BooleanField(default=False)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transcript",
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.call"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcript_events",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["transcript"], name="app_transcript_events_transcript_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["call"], name="app_transcript_events_call_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["company"], name="app_transcript_events_company_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["user"], name="app_transcript_events_user_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["sequence_number"], name="app_transcript_events_sequence_number_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptevent",
            index=models.Index(fields=["created_at"], name="app_transcript_events_created_at_idx"),
        ),
    ]
