# Generated by Django 5.0.1 on 2025-12-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial_core"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="companymembership",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="scorecardsystemprompt",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="summarysystemprompt",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="transcript",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="transcriptevent",
            options={"managed": False},
        ),
    ]
